"""empty message

Revision ID: 3450b35df33a
Revises: 10420c9b6af3
Create Date: 2020-03-19 14:31:25.636971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3450b35df33a'
down_revision = '10420c9b6af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('total_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice', 'total_qty')
    # ### end Alembic commands ###
